INSERT INTO puzzle_images (title, image_path, grid_rows, grid_cols)
VALUES
    ('Aurora Lake', '/puzzle-images/aurora-lake.jpg', 5, 5),
    ('Mountain Sunrise', '/puzzle-images/mountain-sunrise.jpg', 5, 5),
    ('City Nights', '/puzzle-images/city-nights.jpg', 5, 5),
    ('Sakura Skyline', '/puzzle-images/sakura-skyline.jpg', 5, 5),
    ('Neon Rain Alley', '/puzzle-images/neon-rain-alley.jpg', 5, 5),
    ('Celestial Shrine', '/puzzle-images/celestial-shrine.jpg', 5, 5),
    ('Crimson Mecha', '/puzzle-images/crimson-mecha.jpg', 5, 5),
    ('Moonlit Katana', '/puzzle-images/moonlit-katana.jpg', 5, 5),
    ('Lantern Festival', '/puzzle-images/lantern-festival.jpg', 5, 5),
    ('Starlit Dojo', '/puzzle-images/starlit-dojo.jpg', 5, 5),
    ('Cloud Kingdom', '/puzzle-images/cloud-kingdom.jpg', 5, 5),
    ('Emerald Forest Path', '/puzzle-images/emerald-forest-path.jpg', 5, 5),
    ('Sunset Shinkansen', '/puzzle-images/sunset-shinkansen.jpg', 5, 5),
    ('Cyber Drift', '/puzzle-images/cyber-drift.jpg', 5, 5),
    ('Winter Samurai', '/puzzle-images/winter-samurai.jpg', 5, 5),
    ('Comet Harbor', '/puzzle-images/comet-harbor.jpg', 5, 5),
    ('Glass Ocean', '/puzzle-images/glass-ocean.jpg', 5, 5),
    ('Golden Bamboo', '/puzzle-images/golden-bamboo.jpg', 5, 5),
    ('Storm Citadel', '/puzzle-images/storm-citadel.jpg', 5, 5),
    ('Desert Pursuit', '/puzzle-images/desert-pursuit.jpg', 5, 5),
    ('Skyline Heist', '/puzzle-images/skyline-heist.jpg', 5, 5),
    ('Eclipse Runway', '/puzzle-images/eclipse-runway.jpg', 5, 5),
    ('Velvet Noir', '/puzzle-images/velvet-noir.jpg', 5, 5),
    ('Midnight Convoy', '/puzzle-images/midnight-convoy.jpg', 5, 5),
    ('Last Train Home', '/puzzle-images/last-train-home.jpg', 5, 5),
    ('Chrome Frontier', '/puzzle-images/chrome-frontier.jpg', 5, 5),
    ('Dune Rider', '/puzzle-images/dune-rider.jpg', 5, 5),
    ('Auric Vault', '/puzzle-images/auric-vault.jpg', 5, 5),
    ('Titan Hangar', '/puzzle-images/titan-hangar.jpg', 5, 5),
    ('Polar Beacon', '/puzzle-images/polar-beacon.jpg', 5, 5),
    ('Silver Monolith', '/puzzle-images/silver-monolith.jpg', 5, 5),
    ('Ember Canyon', '/puzzle-images/ember-canyon.jpg', 5, 5),
    ('Sapphire Lagoon', '/puzzle-images/sapphire-lagoon.jpg', 5, 5),
    ('Obsidian Castle', '/puzzle-images/obsidian-castle.jpg', 5, 5),
    ('Wildflower Valley', '/puzzle-images/wildflower-valley.jpg', 5, 5),
    ('Moonfall Ruins', '/puzzle-images/moonfall-ruins.jpg', 5, 5),
    ('Solar Garden', '/puzzle-images/solar-garden.jpg', 5, 5),
    ('Thunder Peaks', '/puzzle-images/thunder-peaks.jpg', 5, 5),
    ('Jade River', '/puzzle-images/jade-river.jpg', 5, 5),
    ('Frost Lanterns', '/puzzle-images/frost-lanterns.jpg', 5, 5),
    ('Sunset Carnival', '/puzzle-images/sunset-carnival.jpg', 5, 5),
    ('Nebula Orbit', '/puzzle-images/nebula-orbit.jpg', 5, 5),
    ('Rose Metro', '/puzzle-images/rose-metro.jpg', 5, 5),
    ('Phantom Harbor', '/puzzle-images/phantom-harbor.jpg', 5, 5),
    ('Opal Temple', '/puzzle-images/opal-temple.jpg', 5, 5),
    ('Dusk Arcade', '/puzzle-images/dusk-arcade.jpg', 5, 5),
    ('Dream Courtyard', '/puzzle-images/dream-courtyard.jpg', 5, 5),
    ('Iron Requiem', '/puzzle-images/iron-requiem.jpg', 5, 5),
    ('Velvet Cosmos', '/puzzle-images/velvet-cosmos.jpg', 5, 5),
    ('Horizon Overture', '/puzzle-images/horizon-overture.jpg', 5, 5)
ON CONFLICT (image_path) DO NOTHING;
